VIRTUAL_LLM_URL: "http://localhost:10000/v1/" # Default VLLM URL
BASEDIR: '' 
OPENAI_API_KEY: ""
seed: 42

defaults:
  - _self_
  - llm: ??? # The language model to use
  - defense: ??? # The defense algorithm to use
  - task: ??? # The task to evaluate, including both attack and benign
  - attack: ??? # The attack algorithm to use

hydra:
  run:
    dir: outputs/${hydra.job.name}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs_multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys: []
